---
version: "2.1"
services:
  changedetection:
    image: lscr.io/linuxserver/changedetection.io:latest
    container_name: changedetection
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - BASE_URL= #optional
    volumes:
      - /srv/Docker/changedetection:/config
    ports:
      - 5000:5000
    restart: unless-stopped
