---
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: Duplicati
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - CLI_ARGS= #optional
    ports:
      - 8200:8200
    volumes:
      - /srv/Docker/Duplicati/config:/config
      - /srv/Docker/Duplicati/backups:/backups
      - /srv/Docker/Vaultwarden:/source/Vaultwarden
      - /srv/Docker/Nginx-Proxy-Manager:/source/Nginx-Proxy-Manager
      - /srv/Docker/Heimdall:/source/Heimdall
    restart: unless-stopped
    
