---
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: Heimdall
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    ports:
      - 90:80
      - 455:443
    volumes:
      - /srv/Docker/Heimdall:/config
    restart: unless-stopped
