---
services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: Kasm
    network_mode: bridge
    privileged: true
    environment:
      - KASM_PORT=450
      - DOCKER_HUB_USERNAME=USER `#optional`
      - DOCKER_HUB_PASSWORD=PASS `#optional`
      - DOCKER_MTU=1500 `#optional`
    ports:
      - 3000:3000
      - 450:450
    volumes:
      - /srv/Docker/Kasm/opt:/opt
      - /srv/Docker/Kasm/profiles:/profiles `#optional`
      - /srv/Docker/Kasm/input:/dev/input `#optional`
      - /srv/Docker/Kasm/data:/run/udev/data `#optional`
    restart: unless-stopped
