---
services:
  minecraft-server:
    image: itzg/minecraft-server:latest
    container_name: Minecraft-Server
    network_mode: bridge
    tty: true
    stdin_open: true
    environment:
      EULA: TRUE
      #VERSION: 1.7.9
    ports:
      - 25565:25565
    volumes:
      - /srv/Docker/Minecraft-Server:/data
    restart: unless-stopped
