version: '3.8'
services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: Nginx-Proxy-Manager
    network_mode: bridge
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - /srv/Docker/Nginx-Proxy-Manager/data:/data
      - /srv/Docker/Nginx-Proxy-Manager/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
