---
services:
  ollama:
    image: ollama/ollama:latest
    container_name: Ollama
    network_mode: Nginx-Proxy-Manager-Network
    ports:
      - 11434:11434
    volumes:
      - /srv/Docker/Ollama:/root/.ollama
    restart: unless-stopped
