---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: Plex
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - VERSION=docker
      - PLEX_CLAIM= #optional https://www.plex.tv/claim/
    ports:
      - 32400:32400
    volumes:
      - /srv/Docker/Plex/config:/config
      - /srv/Docker/Plex/SERIES:/tv
      - /srv/Docker/Plex/FILMS:/movies
    restart: unless-stopped
