---
services:
  portainer-agent:
    image: portainer/agent:latest
    container_name: Portainer-Agent
    network_mode: bridge
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: always
