---
services:
  searxng:
    image: searxng/searxng:latest
    container_name: SearXNG
    network_mode: bridge
    environment:
      - BASE_URL=http://localhost:8080
      - INSTANCE_NAME=SearXNG
    ports:
      - 8080:8080
    volumes:
      - /srv/Docker/SearXNG:/etc/searxng
    restart: unless-stopped
