---
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: Vaultwarden
    network_mode: bridge
    ports:
      - 100:80
    volumes:
      - /srv/Docker/Vaultwarden:/data/
    restart: unless-stopped
