version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: Watchtower
    network_mode: bridge
    environment:
      - TZ=Europe/Paris
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE='0 0 0 * * *'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
