---
services:
  wireguard-easy:
    image: weejewel/wg-easy:latest
    container_name: WireGuard-easy
    network_mode: bridge
    cap_add:
      - SYS_MODULE
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    environment:
      - WG_HOST=YOUR_SERVER_IP
      - PASSWORD=YOUR_ADMIN_PASSWORD
    ports:
      - 51820:51820/udp
      - 51821:51821
    volumes:
      - /srv/Docker/WireGuard-easy:/etc/wireguard
    restart: unless-stopped
