---
services:
  conteneur:
    image: conteneur/conteneur:latest
    container_name: Conteneur
    network_mode: bridge
    command: 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    ports:
      - 100:100
      - 200:200
    volumes:
      - /srv/Docker/Conteneur/config:/config 
      - /srv/Docker/Conteneur/data:/data 
    restart: unless-stopped
