---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  cloudflare-token: abc123        # Use your API Token from cloudflare here ( edit + read must be set on it )  